version: "3.2"
services:
  php:
    build: './docker/php/'
    user: 1000:1000
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
  database:
    image: mariadb:10.4.12
    user: 1000:1000
    networks:
      - backend
    volumes:
      - ./mariadb_persistent/:/var/lib/mysql/
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=rootpassword
    tty: true
  web:
    build: './docker/nginx/'
    user: 1000:1000
    depends_on:
      - php
      - database
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/localhost.conf:/etc/nginx/conf.d/localhost.conf
  node:
    build: './docker/node/'
    user: 1000:1000
    depends_on:
      - web
    volumes:
      - ./:/var/www/html/
    tty: true
networks:
  frontend:
  backend: